### PR TITLE
chore(k8s): migrate to context based workflow

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Review by Sh4d1 — CHANGES_REQUESTED** [review]
There is some calls missing ctx like listversions in the helpers file

**Comment by remyleone** [comment]
https://github.com/scaleway/scaleway-sdk-go/pull/575

**Review by Sh4d1 — APPROVED** [review]
LGTM

**Review by Sh4d1 — APPROVED** [review]
LGTM

**Pull request merged**
