### PR TITLE
feat(k8s): remove dashboard and ingress fields

### PR DESCRIPTION
**Pull request by Sh4d1**
Signed-off-by: Patrik Cyvoct <patrik@ptrk.io>

### CODE REVIEW

**Review by remyleone — APPROVED** [review]

**Comment by TommyTheTribe** [comment]
What is the reason for deleting this please ?

**Comment by Sh4d1** [comment]
Hey @TommyTheTribe !
- the dashboard field is now deprecated since you can access it via the Scaleway console without it being deployed on the cluster
- the ingresses will soon be deprecated, and it was easier to remove them from the 2.0 release before, rather than depreciating them after the 2.0 relase was cut. A replacement for the ingresses is on its way, not sure il will be available in Terraform though 🤔 in either case, best way is still to deploy the ingress on your own so you're in full control of the configuration :)

**Comment by TommyTheTribe** [comment]
Ok thanks for response ;)

**Comment by chinochao** [comment]
The dashboard does seems deprecated in the API for Scaleway. 

Is the ingress also getting deprecated from the API? If you guys are not using the addon ingress which does so much more like the ability to deploy LB from Kuberentes then how do you guys accomplish deploying a LB in Scaleway from Kuberentes? I am referring to this. https://www.scaleway.com/en/docs/using-a-load-balancer-to-expose-your-kubernetes-kapsule-ingress-controller-service/

**Comment by Sh4d1** [comment]
@chinochao the ingress is also going to be deprecated soon. There will be a replacement (maybe not available in Terraform though). 
You can either deploy the plain manifest (https://kubernetes.github.io/ingress-nginx/deploy/#scaleway for instance)
Or use Helm on the ingress of your choice :)

**Pull request merged**
