### PR TITLE
fix(docs): s3 storage as terraform backend

### PR DESCRIPTION
**Pull request by sebastienbaillet**
Provided solution can't work as `terraform init` doesn't read env var. One should use `-backend-config`.

### CODE REVIEW

**Comment by sebastienbaillet** [comment]
I read this documentation, but I can't make it work with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY_ID env var (nor ~/.aws/credentials, nor ~/.aws/config), may it be on Windows or on Linux. 
After some tests, it seems that it works only for the provider configuration not for the backend configuration. If you manage to make it work, let me know how you did.

**Comment by sebastienbaillet** [comment]
With the following code:

```
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
    }
  }
  required_version = ">= 0.13"
}

provider "scaleway" {
  zone   = "fr-par-1"
  region = "fr-par"
}

terraform {
  backend "s3" {
    bucket                      = "my-default-storage"
    key                         = "helloworld/helloworld.tfstate"
    region                      = "fr-par"
    endpoint                    = "https://s3.fr-par.scw.cloud"
    skip_credentials_validation = true
    skip_region_validation      = true
  }
}
```

If I try to `terraform init`

```
PS> $env:SCW_ACCESS_KEY='XXXXXXXXXXXXXXXXXXXX'
PS>  $env:SCW_SECRET_KEY='XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
PS> terraform init

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│
│
│
╵

PS> $env:AWS_SECRET_ACCESS_KEY=$env:SCW_ACCESS_KEY
PS> $env:AWS_ACCESS_KEY_ID=$env:SCW_SECRET_KEY
PS> terraform init

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

I've tried to add aws provider, just in case... same result.
Same result on Linux.

**Comment by quantumsheep** [comment]
@sebastienbaillet We tested on our side and worked out well.

You may have set incorrect credentials, can please you try [generating a new key](https://console.scaleway.com/iam/api-keys) and use it ?

**Comment by sebastienbaillet** [comment]
On my PC, it begins to work after I've installed and configure aws cli.
I've made some more tests, it seems that terraform uses default ~/.aws/credentials and not the environment variables. 

Starting a new shell:

```
PS> $env:SCW_ACCESS_KEY='XXXXXXX'
PS>  $env:SCW_SECRET_KEY='XXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
PS> $env:SCW_DEFAULT_ORGANIZATION_ID='XXXXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
PS> terraform init -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of scaleway/scaleway from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Using previously-installed scaleway/scaleway v2.8.0
- Using previously-installed hashicorp/random v3.4.3

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

PS> $env:AWS_ACCESS_KEY_ID=$env:SCW_ACCESS_KEY
PS> $env:AWS_SECRET_ACCESS_KEY=$env:SCW_SECRET_KEY
PS> terraform init -reconfigure

Initializing the backend...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Reusing previous version of scaleway/scaleway from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Using previously-installed scaleway/scaleway v2.8.0
- Using previously-installed hashicorp/random v3.4.3

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

PS> mv ~/.aws/credentials ~/.aws/credentials-back
PS> terraform init -reconfigure

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│       For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│
│
│
╵

```

On GitHub, the following worflow fails:

```yaml
name: helloworld-plan-infrastructure
on: [workflow_dispatch]
jobs:
  plan-infrastructure:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init -reconfigure
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
        working-directory: terraform
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
```

Results:

```
Run terraform init
/home/runner/work/_temp/5f60f5[8](https://github.com/Lupise/helloworld--compose/actions/runs/3787339734/jobs/6439053571#step:4:9)0-a7b0-4[9](https://github.com/Lupise/helloworld--compose/actions/runs/3787339734/jobs/6439053571#step:4:10)9f-b941-1d56ccfe7a72/terraform-bin init

Initializing the backend...
╷
│ Error: error configuring S3 Backend: no valid credential sources for S3 Backend found.
│ 
│ Please see https://www.terraform.io/docs/language/settings/backends/s3.html
│ for more information about providing credentials.
│ 
│ Error: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
│ 
│ 
│ 
╵
```

(I've made some research on the deprecation notice from the last error message without success.)

When you make your tests, did you have ~/.aws directory ?

**Comment by remyleone** [comment]
It was working for me without a `~/.aws` directory on windows

**Pull request closed without merging**
