### PR TITLE
feat(k8s): add support for project id

### PR DESCRIPTION
**Pull request by remyleone**

### CODE REVIEW

**Review by Sh4d1 — CHANGES_REQUESTED** [review]
Forgot to set the project id

**Review by Sh4d1 — APPROVED** [review]
LGTM

**Comment by samhamilton** [comment]
@remyleone do you have any idea when these changes will be released?

**Comment by remyleone** [comment]
Soon. :-) in the mean time you can build the master branch of this repository. It will give you a binary. Swap this binary with the one present in your '.terraform' folder in your project and it should work.

**Comment by samhamilton** [comment]
@remyleone thanks yes it does!

**Pull request merged**
